#!/bin/bash

#       Copyright 2015 Allan Psicobyte
#
#       rankingfaker es una aplicación estúpida para hacer contribuciones espúrias en github (o en cualquier repo, claro)
#
#       This program is free software: you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation, either version 3 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program.  If not, see <http://www.gnu.org/licenses/>.

archivo_entrada="10000pi.txt"
archivo_salida="pi_description"

i=0
cadamil=0

while read -n 1 caracter

do
    case $caracter in
        1)
        palabra="uno"
        ;;
        2)
        palabra="dos"
        ;;
        3)
        palabra="tres"
        ;;
        4)
        palabra="cuatro"
        ;;
        5)
        palabra="cinco"
        ;;
        6)
        palabra="seis"
        ;;
        7)
        palabra="siete"
        ;;
        8)
        palabra="ocho"
        ;;
        9)
        palabra="nueve"
        ;;
        0)
        palabra="cero"
        ;;
        *)
        palabra="algo que no es un dígito"
    esac

    ((i+=1))
    ((cadamil+=1))
    echo "El $i dígito de PI es $palabra." >> $archivo_salida
    git add $archivo_salida
    git commit -m "Agregado el $i dígito de PI a $archivo_salida"

    #Hace un push cada 1000 commits
    if [[ "$cadamil" -eq 1000 ]]; then
         echo "push"

# descomenta esto para que el programa haga push automáticamente (comentado por seguridad)
#        git push
        cadamil=0
    fi

done < "$archivo_entrada"

# descomenta esto para que el programa haga push automáticamente (comentado por seguridad):
#git push

